# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba891c70f8eaa8e1e91789e0a8eda92305233bd3bccdd7693bdac0b3330edbf7b35a2627d2973846ae6d55e8fecc0c5c5640260ae5064a74871c78d3f06f0456

test:
  secret_key_base: fc6ea3df0166714dd3ce3e978288fa7c5e38ac4cae8f42b76b4e9bc183da1e286ea5590cc2a0f7f9d3b8b2859218147cb490b9488989240bd333dbd97dbee9c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
